In [5]:
import sys
sys.path.append('../backend/services')
import course_calendar as cc

In [8]:
cc.create_schedule(term = 'Spring', year = '2026', days = 'TR')

,Day,Date,Description
1,Wednesday,01/21/2026,CLASSES BEGIN 8:00 A.M.
0,Thursday,01/22/2026,
1,Tuesday,01/27/2026,
2,Tuesday,01/27/2026,Open add/drop period ends
3,Wednesday - Tuesday,01/28/2026 - 02/03/2026,Add period; instructor approval required
2,Thursday,01/29/2026,
3,Tuesday,02/03/2026,
4,Thursday,02/05/2026,
5,Tuesday,02/10/2026,
6,Thursday,02/12/2026,
4,Friday - Monday,02/13/2026 - 02/16/2026,"President’s Recess – no classes, offices closed"
7,Tuesday,02/17/2026,
8,Thursday,02/19/2026,
9,Tuesday,02/24/2026,
10,Thursday,02/26/2026,
11,Tuesday,03/03/2026,
12,Thursday,03/05/2026,
13,Tuesday,03/10/2026,
14,Thursday,03/12/2026,
5,Monday - Sunday,03/16/2026 - 03/22/2026,Spring Recess - no classes on campus
15,Tuesday,03/17/2026,
16,Thursday,03/19/2026,
17,Tuesday,03/24/2026,
18,Thursday,03/26/2026,
19,Tuesday,03/31/2026,
20,Thursday,04/02/2026,
6,Friday,04/03/2026,"Day of Reflection/Good Friday – no classes, of..."
21,Tuesday,04/07/2026,
22,Thursday,04/09/2026,
23,Tuesday,04/14/2026,
24,Thursday,04/16/2026,
25,Tuesday,04/21/2026,
7,Thursday,04/23/2026,Credit/no-credit deadline; students submit to ...
26,Thursday,04/23/2026,
8,Friday,04/24/2026,CREATE Student Conference
27,Tuesday,04/28/2026,
28,Thursday,04/30/2026,
29,Tuesday,05/05/2026,
30,Thursday,05/07/2026,
9,Friday,05/08/2026,Last day to withdraw from the University
10,Friday,05/08/2026,Last day of classes

## getSchedule

Example of calling getSchedule endpoint

In [ ]:
import requests

session = requests.Session()

r = session.get('http://127.0.0.1:5000/api/test_login/?user=annie&password=password')

json = {'term': 'Fall',
        'year': '2025',
        'days': 'W'}

schedule = session.post('http://127.0.0.1:5000/api/generateSchedule', json = json)

In [5]:
schedule.text

'{\n  "schedule": [\n    {\n      "Date": "08/26/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "08/26/2025",\n      "Day": "Tuesday",\n      "Description": "CLASSES BEGIN 8:00 A.M."\n    },\n    {\n      "Date": "08/28/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "09/01/2025",\n      "Day": "Monday",\n      "Description": "Labor Day Holiday - no classes, offices closed"\n    },\n    {\n      "Date": "09/02/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "09/02/2025",\n      "Day": "Tuesday",\n      "Description": "Open add/drop period ends"\n    },\n    {\n      "Date": "09/03/2025 - 09/09/2025",\n      "Day": "Wednesday - Tuesday",\n      "Description": "Add period; instructor approval required"\n    },\n    {\n      "Date": "09/04/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "09/09/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "09/11/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "09/16/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "09/18/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "09/23/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "09/25/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "09/30/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "10/02/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "10/07/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "10/09/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "10/14/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "10/16/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "10/21/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "10/23/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "10/28/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "10/30/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "11/04/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "11/06/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "11/11/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "11/13/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "11/18/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "11/20/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "11/25/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "11/26/2025",\n      "Day": "Wednesday",\n      "Description": "University open, no classes scheduled"\n    },\n    {\n      "Date": "11/26/2025 - 11/30/2025",\n      "Day": "Wednesday - Sunday",\n      "Description": "Thanksgiving recess \\u2013 no classes"\n    },\n    {\n      "Date": "11/27/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "12/02/2025",\n      "Day": "Tuesday",\n      "Description": ""\n    },\n    {\n      "Date": "12/04/2025",\n      "Day": "Thursday",\n      "Description": ""\n    },\n    {\n      "Date": "12/05/2025",\n      "Day": "Friday",\n      "Description": "Last day to withdraw from the University"\n    },\n    {\n      "Date": "12/05/2025",\n      "Day": "Friday",\n      "Description": "Last day of classes"\n    }\n  ]\n}\n'

In [3]:
import json
import pandas as pd
j = json.loads(schedule.text)
pd.DataFrame.from_dict(j['schedule'])

,Date,Day,Description
0,08/26/2025,Tuesday,
1,08/26/2025,Tuesday,CLASSES BEGIN 8:00 A.M.
2,08/28/2025,Thursday,
3,09/01/2025,Monday,"Labor Day Holiday - no classes, offices closed"
4,09/02/2025,Tuesday,
5,09/02/2025,Tuesday,Open add/drop period ends
6,09/03/2025 - 09/09/2025,Wednesday - Tuesday,Add period; instructor approval required
7,09/04/2025,Thursday,
8,09/09/2025,Tuesday,
9,09/11/2025,Thursday,
10,09/16/2025,Tuesday,
11,09/18/2025,Thursday,
12,09/23/2025,Tuesday,
13,09/25/2025,Thursday,
14,09/30/2025,Tuesday,
15,10/02/2025,Thursday,
16,10/07/2025,Tuesday,
17,10/09/2025,Thursday,
18,10/14/2025,Tuesday,
19,10/16/2025,Thursday,
20,10/21/2025,Tuesday,
21,10/23/2025,Thursday,
22,10/28/2025,Tuesday,
23,10/30/2025,Thursday,
24,11/04/2025,Tuesday,
25,11/06/2025,Thursday,
26,11/11/2025,Tuesday,
27,11/13/2025,Thursday,
28,11/18/2025,Tuesday,
29,11/20/2025,Thursday,
30,11/25/2025,Tuesday,
31,11/26/2025,Wednesday,"University open, no classes scheduled"
32,11/26/2025 - 11/30/2025,Wednesday - Sunday,Thanksgiving recess – no classes
33,11/27/2025,Thursday,
34,12/02/2025,Tuesday,
35,12/04/2025,Thursday,
36,12/05/2025,Friday,Last day to withdraw from the University
37,12/05/2025,Friday,Last day of classes